spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:h2:mem:test}
    username: ${SPRING_DATASOURCE_USERNAME:sa}
    password: ${SPRING_DATASOURCE_PASSWORD:}
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

client:
  authorizer:
    host: https://run.mocky.io
    path: /v3/5794d450-d2e2-4412-8131-73d0293ac1cc
  notification:
    host: https://run.mocky.io
    path: /v3/54dc2cf1-3add-45b5-b5a9-6bf7e7f1f4a6
