spring:
  datasource:
    url: jdbc:h2:mem:test
    username: ${SPRING_DATASOURCE_USERNAME:sa}
    password: ${SPRING_DATASOURCE_PASSWORD:}
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true