spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/picpay}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update

client:
  authorizer:
    host: https://run.mocky.io
    path: /v3/5794d450-d2e2-4412-8131-73d0293ac1cc
  notification:
    host: https://run.mocky.io
    path: /v3/54dc2cf1-3add-45b5-b5a9-6bf7e7f1f4a6
